### ISSUE TITLE
How is connect with plugin :multi_route

### ISSUE THREAD

**Issue by randsina** [jeremyevans/roda-route_list#2]
Hi.
Is any opportunity connect this gem with plugin :multi_route?
```sh
$ roda-parse_routes -f routes.json app.rb
```
This command see only routes in `app.rb`. I have directory `routes` with few files which required in `app.rb`
`Dir['./routes/*.rb'].each { |file| require file }`

**Comment by jeremyevans** [comment]
You can provide multiple files: `roda-parse_routes -f routes.json app.rb routes/*.rb`.  This is mentioned in the help for the command:`Usage: roda-parse_routes [options] [file] ...`.
